debug = false
disable_crowdin = false
check_for_updates = true

[activations.4aec07ba-d109-3345-9a0a-92022a116cd0]
toggle = false
type = "VOICE"
[activations.46927964-3207-377a-84d7-26a82d52be1e]
toggle = true
type = "VOICE"
[activations.b01b59f4-6556-35a0-9160-e955dc606352]
toggle = true
type = "VOICE"
[[key_bindings]]
name = "key.plasmovoice.general.disable_voice"
any_context = false
category = "key.plasmovoice.general"

[[key_bindings.keys]]
code = 78
type = "KEYSYM"

[[key_bindings]]
name = "key.plasmovoice.broadcast.toggle"
any_context = false
category = "hidden"

[[key_bindings.keys]]
code = 96
type = "KEYSYM"

[[key_bindings]]
name = "key.plasmovoice.groups.ptt"
any_context = true
category = "hidden"

[[key_bindings.keys]]
code = 71
type = "KEYSYM"

[[key_bindings]]
name = "key.plasmovoice.groups.toggle"
any_context = false
category = "hidden"

[[key_bindings.keys]]
code = 71
type = "KEYSYM"

[[key_bindings]]
name = "key.plasmovoice.proximity.distance_increase"
any_context = false
category = "hidden"

[[key_bindings.keys]]
code = 91
type = "KEYSYM"

[[key_bindings]]
name = "key.plasmovoice.proximity.distance_decrease"
any_context = false
category = "hidden"

[[key_bindings.keys]]
code = 93
type = "KEYSYM"

[servers.d116a02e-e80b-4672-961d-e0a71148b099.distances]
4aec07ba-d109-3345-9a0a-92022a116cd0 = 32
[servers.8fe5a797-a699-47a0-8195-b6cb4c8576ea.distances]
4aec07ba-d109-3345-9a0a-92022a116cd0 = 32


[voice]
disabled = false
microphone_disabled = false
activation_threshold = -50.0
input_device = ""
output_device = ""
disable_input_device = false
use_javax_input = false
microphone_volume = 2.0
noise_suppression = false
volume = 1.0
compressor_limiter = true
sound_occlusion = false
directional_sources = false
hrtf = false
stereo_capture = false

[voice.volumes.broadcast]
volume = 1.0
[voice.volumes.proximity]
volume = 1.0
[voice.volumes.groups]
volume = 1.0

[advanced]
visualize_voice_distance = true
visualize_voice_distance_on_join = false
compressor_threshold = -10
limiter_threshold = -6
directional_sources_angle = 360
stereo_sources_to_mono = false
panning = true
mute_player_on_direct = true
camera_sound_listener = true
exponential_volume_slider = true
exponential_distance_gain = false
jitter_packet_delay = 3
al_playback_buffers = 5
adaptive_jitter_buffer = false

[overlay]
show_activation_icon = true
activation_icon_position = "BOTTOM_LEFT"
show_source_icons = 1
show_static_source_icons = true
overlay_enabled = true
overlay_position = "TOP_LEFT"
overlay_style = "NAME_SKIN"

[overlay.source_states]
broadcast = "ON"
proximity = "ON"
groups = "WHEN_TALKING"
